// <auto-generated />
using System;
using DeliverySystemV1._1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeliverySystemV1._1.Migrations
{
    [DbContext(typeof(DeliverySystemDbContext))]
    partial class DeliverySystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeliverySystemV1._1.Models.CargoShipments", b =>
                {
                    b.Property<int>("ShipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShipmentId"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RecipientId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<string>("TargetCargoAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ShipmentId");

                    b.ToTable("CargoShipments");

                    b.HasDiscriminator<string>("Discriminator").HasValue("CargoShipments");

                    b.HasData(
                        new
                        {
                            ShipmentId = 2,
                            RecipientId = 3,
                            SenderId = 1,
                            TargetCargoAddress = "Ankara"
                        },
                        new
                        {
                            ShipmentId = 4,
                            RecipientId = 4,
                            SenderId = 3,
                            TargetCargoAddress = "İstanbul"
                        });
                });

            modelBuilder.Entity("DeliverySystemV1._1.Models.CargoTrack", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TrackId"));

                    b.Property<int>("CargoShipmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Coordinate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeliveryDateTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DepartureDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("TrackId");

                    b.ToTable("CargoTracks");
                });

            modelBuilder.Entity("DeliverySystemV1._1.Models.Customer", b =>
                {
                    b.Property<int>("DeliveryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerSurname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("CustomerType")
                        .HasColumnType("smallint");

                    b.Property<int>("Phone")
                        .HasColumnType("integer");

                    b.Property<int>("TcIdentificationNumber")
                        .HasColumnType("integer");

                    b.HasKey("DeliveryID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DeliverySystemV1._1.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Weightiness")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DeliverySystemV1._1.Models.Sender", b =>
                {
                    b.HasBaseType("DeliverySystemV1._1.Models.CargoShipments");

                    b.Property<int>("Test")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Sender");
                });
#pragma warning restore 612, 618
        }
    }
}
